name: Build Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - run: flutter pub get
      - run: flutter build apk --release --no-shrink

      - uses: actions/upload-artifact@v4
        with:
          name: aasj-bs-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
